# Generated by Django 5.1.6 on 2025-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
